//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean Teleport
        {
            get
            {
                return SteamVR_Actions.default_Teleport;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.default_Pose;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonLeftHand;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonRightHand;
            }
        }
        
        public virtual SteamVR_Action_Boolean ToolActionClick
        {
            get
            {
                return SteamVR_Actions.default_ToolActionClick;
            }
        }
        
        public virtual SteamVR_Action_Single ToolActionVariable
        {
            get
            {
                return SteamVR_Actions.default_ToolActionVariable;
            }
        }
        
        public virtual SteamVR_Action_Boolean SwapAction
        {
            get
            {
                return SteamVR_Actions.default_SwapAction;
            }
        }
        
        public virtual SteamVR_Action_Vector2 MenuPosition
        {
            get
            {
                return SteamVR_Actions.default_MenuPosition;
            }
        }
        
        public virtual SteamVR_Action_Boolean MenuActionClick
        {
            get
            {
                return SteamVR_Actions.default_MenuActionClick;
            }
        }
        
        public virtual SteamVR_Action_Boolean MenuDisplay
        {
            get
            {
                return SteamVR_Actions.default_MenuDisplay;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.default_Haptic;
            }
        }
    }
}
